# -*- coding: utf-8 -*-
"""Personalized_Medicine_Recommending_System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BH6kW-xJ_OEeVrIl2igDcQAolU_gSGgv

# Project Name: Personalized Medicine Recommending System


## Ritik Srivastava
"""

df=pd.read_csv('medicine.csv')

# Load saved model (1-2 seconds vs 30+ seconds recompute)
import pandas as pd
import pickle
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

# Load everything instantly
new_df = pd.DataFrame(pickle.load(open('medicine_dict.pkl', 'rb')))
similarity = pickle.load(open('similarity.pkl', 'rb'))

print("✅ Model loaded! Ready for recommendations.")
print(f"Dataset size: {new_df.shape}")

df.head()

df.shape

df.isnull().sum()

df.dropna(inplace=True)

df.duplicated().sum()

df['Description']

df['Description'].apply(lambda x:x.split())

df['Reason'] = df['Reason'].apply(lambda x:x.split())
df['Description'] = df['Description'].apply(lambda x:x.split())

df['Description'] = df['Description'].apply(lambda x:[i.replace(" ","") for i in x])

df['tags'] = df['Description'] + df['Reason']

new_df = df[['index','Drug_Name','tags']]

new_df

new_df['tags'].apply(lambda x:" ".join(x))

new_df

new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

new_df

new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

new_df

import nltk

from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(stop_words='english',max_features=5000)

def stem(text):
  y = []

  for i in text.split():
    y.append(ps.stem(i))

  return " ".join(y)

new_df['tags'] = new_df['tags'].apply(stem)

cv.fit_transform(new_df['tags']).toarray().shape

vectors = cv.fit_transform(new_df['tags']).toarray()

cv.get_feature_names_out()

from sklearn.metrics.pairwise import cosine_similarity

cosine_similarity(vectors)

similarity = cosine_similarity(vectors)

similarity[1]

print("Available variables:")
for name in ['new_df', 'newdf', 'df', 'newdf']:
    if name in globals():
        print(f"✅ {name}:", globals()[name].shape if hasattr(globals()[name], 'shape') else type(globals()[name]))
    else:
        print(f"❌ {name}: NOT DEFINED")

def interactive_recommend():
    print("=== Medicine Recommendation System ===")
    print("Available medicines (sample):")
    print(new_df['Drug_Name'].head().tolist())  # ✅ Uses YOUR new_df + Drug_Name
    print("-" * 50)

    while True:
        user_input = input("\nEnter medicine name (or 'quit' to exit): ").strip()

        if user_input.lower() == 'quit':
            print("Thank you for using Medicine Recommendation System!")
            break

        # ✅ Exact match using YOUR new_df['Drug_Name']
        matches = new_df[new_df['Drug_Name'].str.contains(user_input, case=False, na=False)]

        if matches.empty:
            print(f"No medicine found matching '{user_input}'. Try:")
            # Show close matches using first word
            first_word = user_input.split()[0]
            close_matches = new_df[new_df['Drug_Name'].str.contains(first_word, case=False, na=False)].head(3)
            if not close_matches.empty:
                print("Close matches:", close_matches['Drug_Name'].tolist())
            continue

        # ✅ Use first match
        selected_medicine = matches.iloc[0]['Drug_Name']
        print(f"\nFound: {selected_medicine}")
        print("Recommended similar medicines:")
        recommend(selected_medicine)  # ✅ YOUR recommend function

# Run it NOW
interactive_recommend()